# Run code checks.

name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch: { }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "24"
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check lints
        run: npm run lint
      - name: Check formatting
        run: npm run format:check
      - name: Check dependencies
        run: npm audit --audit-level=low
      - name: Check TODOs
        run: bash -x .github/workflows/scripts/check_todos.sh
      - name: Check encoding
        run: isutf8 **/*
